version: 2

build:
    os: "ubuntu-22.04"
    tools:
        python: "mambaforge-22.9"

conda:
    environment: .rtd-environment.yml

python:
    install:
      - method: pip
        path: .

sphinx:
    configuration: docs/conf.py
