language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install -U pytest pytest-cov codecov coveralls
  - pip install tox-travis
  - pip install scrutinizer-ocular
  - pip install pandas
  - pip install -e ".[all]"
script:
  - py.test -v --doctest-glob='*.md' --cov src
after_success:
  - codecov
  - coveralls
  - ocular --data-file ".coverage"
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  - provider: pypi
    edge: true
    server: https://test.pypi.org/legacy/
    user: __token__
    password:
      secure: OzHf1iuJFsQaRXF6g+DdEg41Cz0awEB+QOeYk3Qcl27CUhhMrBFt5zA+VsclWWHTVvx/TgShRld44h4qcu5bxpClrh5H66Kk//xCobAv4Neyjm8cYohzTzQ3k0Oh9y7oAGa4d49rWma5D151elV4qhW1LxnYR0Tx8HeUMfIuFAulG0w590UFDl6Ppd0k6RVBiMMHgInKbMFnOkdPm2/QYu52rvlkqK+cOue6cjl+fHgNuWfBbxRMRm0Z8p0hm44pnWUnm4RLPZ0yHMxMuMnJdg5bpcZKC3mybY6VFlmFJ6JHe/tTPXeXQeGxkHqusSPYk4WR5I8ZWtetDTnqqeboup2Rp1fpebTYqihlDHo3TV+kVIDpHsNlXWHfDhy+zYHQ8KXLi8fFoQfE2FwxSEik0JNhsLsD41pbWguwOLGpKO9YHd/WceU3aneMXygMnthnEseCDY8bJQPFLsWk0bDvqio2iYW0ShcFt7E5JDhU/BuMiYj6eFsaWxEstJCb2FtR4tNZeMBpJnSkoasJTXa+0IJaQ6S+1qh6U5/JpAiM1ej0eEuYcxQfNZxTpKLi+A23bqxBLfPyzbV+LoUvoO9nzU9AhwptQwFZteN/bpFHUYIzuF84Q7paj6PNxv/DBhrpIEy1AjRIDy/yCFUTdkC7Bh8z/VB18qkagZ7d7wcRN9c=
    skip_existing: true
    distributions: sdist bdist_wheel
    on:
      repo: st-bender/pyspaceweather
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION == 3.7
  - provider: pypi
    edge: true
    user: __token__
    password:
      secure: ePsk9dARXmfjc5BImOEf7LY0SjIvbcRcW8Gp907lx0Wic4DiGGVrnvj/hqPzIByuJzGcQsYNAw/XXOMOPzzzQKPybI3Byi+jq3R111o096zTBCbtTmJMFoeYbLE7eaY2wALwY6jUhjsRGpYJ1bgbwd2IIP5n5jhOEdMLoJrwX/uxdnziTLCLNGHmsLafdNbrCMXMAdciNUXvT4845Sbhg2YildA+RZhuNWdLJIso2yQGKrZ6GQV2eZIPxn1pOxOCsb5M+XQ72nGyU/5wfKkAT4y9+fJtMrdrNQCJpkzUrTBD6/gd+fZEQ0EDxjS8ORG7f+iw1Qap0iXnPqeBGJEMgf1/oop/BGbtsXchhGS4CoEiyuWCk7V+Wm2vlDsQqr90Gez9z5El04ljT9nG+AbX4PxnzoTTuYJTgsMhkG60Ux7wgWUAteT0IWld0NN8wzDQT81+lRNmIp32+E4K1ZAs6HDIVRinXAIfyC13uApSSnN3UwFTYmkWIYaijLl7P2ovGrCfuQZPaS43f+dF7cAg5nCvcwwK5rdnlU5m2T7ZwMBuz+DNV/AQ2LC8Tq7obn6YIMh865t2WONttk4lGb1NeQ8gArTKBVeqiNUWvXgySaKTuogx+JCQxL27ByBT++t3vtAie/HHRS0rBrrTUGIQ7h3GGQHgeTMlFZXeOVjFwdY=
    skip_existing: true
    distributions: sdist bdist_wheel
    on:
      repo: st-bender/pyspaceweather
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION == 3.7
